
language: php
 
# Versions of PHP you want your project run with.
 
php:
 
 - 5.5
 
 - 5.6
 
 - 7.0
 
 - 7.1
 
 - 7.2
 
 script:
- echo "skipping tests"

after_deploy:
  - echo "done deploying"

deploy:
 provider: elasticbeanstalk
  access_key_id: "Encrypted <access-key-id>=AKIAIJ22DB2EUHSTIWSA"
  secret_access_key:
    secure: "Encypted <secret-access-key>=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"
  region: "us-east-2"  
  app: "Ezshare-env"
  env: "e-n3uqa32tq4"
  bucket_name: "Ezshare-env.m2ep5wyccr.us-west-2.elasticbeanstalk.com"